const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

const foods = [
  {
    "id": "sle001",
    "food_code": "SLE001",
    "name": "Apple, green",
    "category": "Fruit",
    "calories_per_100g": 51.0,
    "protein_g": 0.46,
    "fat_g": 0.5,
    "carbs_g": 10.65,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle002",
    "food_code": "SLE002",
    "name": "Apple, red",
    "category": "Fruit",
    "calories_per_100g": 62.0,
    "protein_g": 0.29,
    "fat_g": 0.64,
    "carbs_g": 13.11,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle003",
    "food_code": "SLE003",
    "name": "Avocado fruit",
    "category": "Fruit",
    "calories_per_100g": 144.0,
    "protein_g": 2.95,
    "fat_g": 13.86,
    "carbs_g": 1.75,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle004",
    "food_code": "SLE004",
    "name": "Bael fruit",
    "category": "Fruit",
    "calories_per_100g": 133.0,
    "protein_g": 2.63,
    "fat_g": 0.57,
    "carbs_g": 28.21,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle005",
    "food_code": "SLE005",
    "name": "Banana, ripe, ambul",
    "category": "Fruit",
    "calories_per_100g": 109.0,
    "protein_g": 1.11,
    "fat_g": 1.09,
    "carbs_g": 23.37,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle006",
    "food_code": "SLE006",
    "name": "Banana, ripe, anamalu",
    "category": "Fruit",
    "calories_per_100g": 102.0,
    "protein_g": 1.04,
    "fat_g": 0.72,
    "carbs_g": 22.5,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle007",
    "food_code": "SLE007",
    "name": "Banana, ripe, pome",
    "category": "Fruit",
    "calories_per_100g": 110.0,
    "protein_g": 1.25,
    "fat_g": 0.32,
    "carbs_g": 24.95,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle008",
    "food_code": "SLE008",
    "name": "Banana, ripe, silk",
    "category": "Fruit",
    "calories_per_100g": 107.0,
    "protein_g": 1.38,
    "fat_g": 0.34,
    "carbs_g": 23.92,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle009",
    "food_code": "SLE009",
    "name": "Banana, ripe, red",
    "category": "Fruit",
    "calories_per_100g": 111.0,
    "protein_g": 1.29,
    "fat_g": 0.29,
    "carbs_g": 25.21,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle010",
    "food_code": "SLE010",
    "name": "Banana, ripe, Cavendish",
    "category": "Fruit",
    "calories_per_100g": 99.0,
    "protein_g": 1.14,
    "fat_g": 0.33,
    "carbs_g": 22.41,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle011",
    "food_code": "SLE011",
    "name": "Black-purple berries, Java plum",
    "category": "Fruit",
    "calories_per_100g": 56.0,
    "protein_g": 0.9,
    "fat_g": 0.65,
    "carbs_g": 10.95,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle012",
    "food_code": "SLE012",
    "name": "Ceylon olive",
    "category": "Fruit",
    "calories_per_100g": 80.0,
    "protein_g": 1.48,
    "fat_g": 0.27,
    "carbs_g": 17.73,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle013",
    "food_code": "SLE013",
    "name": "Custard apple, sweetsop",
    "category": "Fruit",
    "calories_per_100g": 98.0,
    "protein_g": 1.62,
    "fat_g": 0.67,
    "carbs_g": 20.38,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle014",
    "food_code": "SLE014",
    "name": "Dates, processed",
    "category": "Fruit",
    "calories_per_100g": 285.0,
    "protein_g": 1.28,
    "fat_g": 0.41,
    "carbs_g": 67.71,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle015",
    "food_code": "SLE015",
    "name": "Gooseberry, Indian",
    "category": "Fruit",
    "calories_per_100g": 26.0,
    "protein_g": 0.33,
    "fat_g": 0.16,
    "carbs_g": 5.31,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle016",
    "food_code": "SLE016",
    "name": "Grapes, seeded, round, black",
    "category": "Fruit",
    "calories_per_100g": 60.0,
    "protein_g": 0.76,
    "fat_g": 0.32,
    "carbs_g": 13.23,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle017",
    "food_code": "SLE017",
    "name": "Grapes, seeded, round, green",
    "category": "Fruit",
    "calories_per_100g": 55.0,
    "protein_g": 0.62,
    "fat_g": 0.31,
    "carbs_g": 12.13,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle018",
    "food_code": "SLE018",
    "name": "Grapes, seeded, round, red",
    "category": "Fruit",
    "calories_per_100g": 49.0,
    "protein_g": 0.95,
    "fat_g": 0.23,
    "carbs_g": 10.69,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle019",
    "food_code": "SLE019",
    "name": "Grapes, seeded, oval, black",
    "category": "Fruit",
    "calories_per_100g": 99.0,
    "protein_g": 1.72,
    "fat_g": 0.64,
    "carbs_g": 20.99,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle020",
    "food_code": "SLE020",
    "name": "Grapes, seedless, round, green",
    "category": "Fruit",
    "calories_per_100g": 58.0,
    "protein_g": 0.68,
    "fat_g": 0.25,
    "carbs_g": 12.93,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle021",
    "food_code": "SLE021",
    "name": "Guava, kilo pera",
    "category": "Fruit",
    "calories_per_100g": 39.0,
    "protein_g": 1.53,
    "fat_g": 0.38,
    "carbs_g": 6.88,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle022",
    "food_code": "SLE022",
    "name": "Guava, pink flesh",
    "category": "Fruit",
    "calories_per_100g": 47.0,
    "protein_g": 1.14,
    "fat_g": 0.27,
    "carbs_g": 9.48,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle023",
    "food_code": "SLE023",
    "name": "Guava, white flesh",
    "category": "Fruit",
    "calories_per_100g": 31.0,
    "protein_g": 1.5,
    "fat_g": 0.31,
    "carbs_g": 4.85,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle024",
    "food_code": "SLE024",
    "name": "Jack fruit, ripe",
    "category": "Fruit",
    "calories_per_100g": 72.0,
    "protein_g": 3.3,
    "fat_g": 0.14,
    "carbs_g": 13.49,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle025",
    "food_code": "SLE025",
    "name": "Jamun fruit, rose apple, white",
    "category": "Fruit",
    "calories_per_100g": 56.0,
    "protein_g": 0.67,
    "fat_g": 0.18,
    "carbs_g": 12.55,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle026",
    "food_code": "SLE026",
    "name": "Karonda fruit",
    "category": "Fruit",
    "calories_per_100g": 33.0,
    "protein_g": 1.15,
    "fat_g": 1.67,
    "carbs_g": 2.87,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle027",
    "food_code": "SLE027",
    "name": "Lemon, juice",
    "category": "Fruit",
    "calories_per_100g": 38.0,
    "protein_g": 0.37,
    "fat_g": 0.76,
    "carbs_g": 7.36,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle028",
    "food_code": "SLE028",
    "name": "Lime, sweet, pulp",
    "category": "Fruit",
    "calories_per_100g": 26.0,
    "protein_g": 0.66,
    "fat_g": 0.26,
    "carbs_g": 4.99,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle029",
    "food_code": "SLE029",
    "name": "Mandarine, heen naran",
    "category": "Fruit",
    "calories_per_100g": 46.0,
    "protein_g": 1.07,
    "fat_g": 0.37,
    "carbs_g": 9.27,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle030",
    "food_code": "SLE030",
    "name": "Mango, ripe, bud",
    "category": "Fruit",
    "calories_per_100g": 40.0,
    "protein_g": 0.57,
    "fat_g": 0.57,
    "carbs_g": 7.67,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle031",
    "food_code": "SLE031",
    "name": "Mango, ripe, karthakolomban",
    "category": "Fruit",
    "calories_per_100g": 79.0,
    "protein_g": 0.8,
    "fat_g": 0.92,
    "carbs_g": 16.7,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle032",
    "food_code": "SLE032",
    "name": "Mango, ripe, Tom EJC",
    "category": "Fruit",
    "calories_per_100g": 75.0,
    "protein_g": 0.76,
    "fat_g": 0.98,
    "carbs_g": 15.49,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle033",
    "food_code": "SLE033",
    "name": "Mango, ripe, vilad",
    "category": "Fruit",
    "calories_per_100g": 44.0,
    "protein_g": 0.76,
    "fat_g": 0.58,
    "carbs_g": 8.44,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle034",
    "food_code": "SLE034",
    "name": "Mangosteen",
    "category": "Fruit",
    "calories_per_100g": 52.0,
    "protein_g": 0.63,
    "fat_g": 0.24,
    "carbs_g": 11.41,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle035",
    "food_code": "SLE035",
    "name": "Manila tamarind",
    "category": "Fruit",
    "calories_per_100g": 81.0,
    "protein_g": 3.56,
    "fat_g": 1.14,
    "carbs_g": 13.54,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle036",
    "food_code": "SLE036",
    "name": "Musk melon, cantaloupe",
    "category": "Fruit",
    "calories_per_100g": 23.0,
    "protein_g": 0.38,
    "fat_g": 0.38,
    "carbs_g": 4.46,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle037",
    "food_code": "SLE037",
    "name": "Palm fruit, tender",
    "category": "Fruit",
    "calories_per_100g": 24.0,
    "protein_g": 0.5,
    "fat_g": 0.12,
    "carbs_g": 4.92,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle038",
    "food_code": "SLE038",
    "name": "Papaya, ripe",
    "category": "Fruit",
    "calories_per_100g": 26.0,
    "protein_g": 0.42,
    "fat_g": 0.16,
    "carbs_g": 5.28,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle039",
    "food_code": "SLE039",
    "name": "Passion fruit, seeded, yellow",
    "category": "Fruit",
    "calories_per_100g": 83.0,
    "protein_g": 2.33,
    "fat_g": 2.42,
    "carbs_g": 12.64,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle040",
    "food_code": "SLE040",
    "name": "Pear",
    "category": "Fruit",
    "calories_per_100g": 37.0,
    "protein_g": 0.4,
    "fat_g": 0.29,
    "carbs_g": 8.08,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle041",
    "food_code": "SLE041",
    "name": "Pineapple",
    "category": "Fruit",
    "calories_per_100g": 37.0,
    "protein_g": 0.41,
    "fat_g": 0.17,
    "carbs_g": 8.23,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle042",
    "food_code": "SLE042",
    "name": "Pomegranate, maroon seeds",
    "category": "Fruit",
    "calories_per_100g": 55.0,
    "protein_g": 1.42,
    "fat_g": 0.11,
    "carbs_g": 11.8,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle043",
    "food_code": "SLE043",
    "name": "Pummelo",
    "category": "Fruit",
    "calories_per_100g": 43.0,
    "protein_g": 0.63,
    "fat_g": 0.43,
    "carbs_g": 8.99,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle044",
    "food_code": "SLE044",
    "name": "Raisins, dried, black",
    "category": "Fruit",
    "calories_per_100g": 308.0,
    "protein_g": 2.65,
    "fat_g": 0.37,
    "carbs_g": 71.83,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle045",
    "food_code": "SLE045",
    "name": "Raisins, dried, golden",
    "category": "Fruit",
    "calories_per_100g": 294.0,
    "protein_g": 2.54,
    "fat_g": 0.32,
    "carbs_g": 68.74,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle046",
    "food_code": "SLE046",
    "name": "Rambutan",
    "category": "Fruit",
    "calories_per_100g": 73.0,
    "protein_g": 0.68,
    "fat_g": 0.16,
    "carbs_g": 16.84,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle047",
    "food_code": "SLE047",
    "name": "Sapota",
    "category": "Fruit",
    "calories_per_100g": 78.0,
    "protein_g": 0.9,
    "fat_g": 1.28,
    "carbs_g": 15.02,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle048",
    "food_code": "SLE048",
    "name": "Soursop",
    "category": "Fruit",
    "calories_per_100g": 62.0,
    "protein_g": 0.74,
    "fat_g": 0.94,
    "carbs_g": 11.94,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle049",
    "food_code": "SLE049",
    "name": "Star fruit",
    "category": "Fruit",
    "calories_per_100g": 26.0,
    "protein_g": 0.79,
    "fat_g": 0.39,
    "carbs_g": 4.51,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle050",
    "food_code": "SLE050",
    "name": "Strawberry",
    "category": "Fruit",
    "calories_per_100g": 24.0,
    "protein_g": 0.97,
    "fat_g": 0.56,
    "carbs_g": 3.4,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle051",
    "food_code": "SLE051",
    "name": "Tamarind, pulp",
    "category": "Fruit",
    "calories_per_100g": 289.0,
    "protein_g": 2.48,
    "fat_g": 0.15,
    "carbs_g": 67.98,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle052",
    "food_code": "SLE052",
    "name": "Water melon, dark green",
    "category": "Fruit",
    "calories_per_100g": 19.0,
    "protein_g": 0.65,
    "fat_g": 0.16,
    "carbs_g": 3.54,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle053",
    "food_code": "SLE053",
    "name": "Water melon, pale green",
    "category": "Fruit",
    "calories_per_100g": 16.0,
    "protein_g": 0.62,
    "fat_g": 0.15,
    "carbs_g": 3.01,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sle054",
    "food_code": "SLE054",
    "name": "Wood Apple",
    "category": "Fruit",
    "calories_per_100g": 78.0,
    "protein_g": 3.09,
    "fat_g": 3.62,
    "carbs_g": 7.43,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb001",
    "food_code": "SLB001",
    "name": "Beet root",
    "category": "Root Vegetable",
    "calories_per_100g": 31.0,
    "protein_g": 2.12,
    "fat_g": 0.15,
    "carbs_g": 5.01,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb002",
    "food_code": "SLB002",
    "name": "Carrot, orange",
    "category": "Root Vegetable",
    "calories_per_100g": 30.0,
    "protein_g": 0.85,
    "fat_g": 0.45,
    "carbs_g": 5.04,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb003",
    "food_code": "SLB003",
    "name": "Colocasia (taro)",
    "category": "Root Vegetable",
    "calories_per_100g": 87.0,
    "protein_g": 3.96,
    "fat_g": 0.15,
    "carbs_g": 16.95,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb004",
    "food_code": "SLB004",
    "name": "Lasia stalk",
    "category": "Root Vegetable",
    "calories_per_100g": 27.0,
    "protein_g": 0.64,
    "fat_g": 0.16,
    "carbs_g": 5.53,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb005",
    "food_code": "SLB005",
    "name": "Lotus root",
    "category": "Root Vegetable",
    "calories_per_100g": 79.0,
    "protein_g": 1.94,
    "fat_g": 0.93,
    "carbs_g": 14.67,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb006",
    "food_code": "SLB006",
    "name": "Potato, brown skin",
    "category": "Root Vegetable",
    "calories_per_100g": 71.0,
    "protein_g": 1.67,
    "fat_g": 0.25,
    "carbs_g": 15.09,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb007",
    "food_code": "SLB007",
    "name": "Radish, elongated, white skin",
    "category": "Root Vegetable",
    "calories_per_100g": 35.0,
    "protein_g": 0.76,
    "fat_g": 0.12,
    "carbs_g": 7.44,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb008",
    "food_code": "SLB008",
    "name": "Radish, round, red skin",
    "category": "Root Vegetable",
    "calories_per_100g": 31.0,
    "protein_g": 0.89,
    "fat_g": 0.16,
    "carbs_g": 6.07,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb009",
    "food_code": "SLB009",
    "name": "Radish, round, white skin",
    "category": "Root Vegetable",
    "calories_per_100g": 29.0,
    "protein_g": 0.75,
    "fat_g": 0.11,
    "carbs_g": 5.87,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb010",
    "food_code": "SLB010",
    "name": "Sweet potato, pink skin",
    "category": "Root Vegetable",
    "calories_per_100g": 108.0,
    "protein_g": 1.27,
    "fat_g": 0.33,
    "carbs_g": 23.93,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb011",
    "food_code": "SLB011",
    "name": "Tapioca (cassava)",
    "category": "Root Vegetable",
    "calories_per_100g": 78.0,
    "protein_g": 0.92,
    "fat_g": 0.19,
    "carbs_g": 17.58,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb012",
    "food_code": "SLB012",
    "name": "Yam, elephant",
    "category": "Root Vegetable",
    "calories_per_100g": 84.0,
    "protein_g": 2.22,
    "fat_g": 0.15,
    "carbs_g": 17.83,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slb013",
    "food_code": "SLB013",
    "name": "Yam, wild",
    "category": "Root Vegetable",
    "calories_per_100g": 103.0,
    "protein_g": 3.2,
    "fat_g": 0.3,
    "carbs_g": 20.89,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld001",
    "food_code": "SLD001",
    "name": "Amaranth leaves, green",
    "category": "Vegetable",
    "calories_per_100g": 32.0,
    "protein_g": 3.55,
    "fat_g": 0.72,
    "carbs_g": 2.32,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld002",
    "food_code": "SLD002",
    "name": "Amaranth leaves, red",
    "category": "Vegetable",
    "calories_per_100g": 33.0,
    "protein_g": 3.93,
    "fat_g": 0.63,
    "carbs_g": 2.37,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld003",
    "food_code": "SLD003",
    "name": "Amaranth, spinosus, green",
    "category": "Vegetable",
    "calories_per_100g": 26.0,
    "protein_g": 3.75,
    "fat_g": 0.36,
    "carbs_g": 1.37,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld004",
    "food_code": "SLD004",
    "name": "Ambarella",
    "category": "Vegetable",
    "calories_per_100g": 37.0,
    "protein_g": 0.73,
    "fat_g": 0.44,
    "carbs_g": 7.46,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld005",
    "food_code": "SLD005",
    "name": "Ash gourd",
    "category": "Vegetable",
    "calories_per_100g": 18.0,
    "protein_g": 0.8,
    "fat_g": 0.15,
    "carbs_g": 3.16,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld006",
    "food_code": "SLD006",
    "name": "Bean, scarlet, tender",
    "category": "Vegetable",
    "calories_per_100g": 46.0,
    "protein_g": 2.85,
    "fat_g": 0.98,
    "carbs_g": 6.26,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld007",
    "food_code": "SLD007",
    "name": "Beans, fava",
    "category": "Vegetable",
    "calories_per_100g": 30.0,
    "protein_g": 3.95,
    "fat_g": 0.15,
    "carbs_g": 2.19,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld008",
    "food_code": "SLD008",
    "name": "Beans, field, tender",
    "category": "Vegetable",
    "calories_per_100g": 30.0,
    "protein_g": 3.95,
    "fat_g": 0.15,
    "carbs_g": 2.19,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld009",
    "food_code": "SLD009",
    "name": "Beans, French, country",
    "category": "Vegetable",
    "calories_per_100g": 26.0,
    "protein_g": 2.68,
    "fat_g": 0.24,
    "carbs_g": 3.04,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld010",
    "food_code": "SLD010",
    "name": "Beans, French, hybrid",
    "category": "Vegetable",
    "calories_per_100g": 22.0,
    "protein_g": 2.12,
    "fat_g": 0.19,
    "carbs_g": 2.63,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld011",
    "food_code": "SLD011",
    "name": "Beans, long, red",
    "category": "Vegetable",
    "calories_per_100g": 24.0,
    "protein_g": 3.36,
    "fat_g": 0.3,
    "carbs_g": 1.99,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld012",
    "food_code": "SLD012",
    "name": "Beet greens",
    "category": "Vegetable",
    "calories_per_100g": 37.0,
    "protein_g": 2.05,
    "fat_g": 0.76,
    "carbs_g": 4.85,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld013",
    "food_code": "SLD013",
    "name": "Bitter gourd, elongate",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 1.47,
    "fat_g": 0.23,
    "carbs_g": 2.51,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld014",
    "food_code": "SLD014",
    "name": "Bitter gourd, short",
    "category": "Vegetable",
    "calories_per_100g": 17.0,
    "protein_g": 1.21,
    "fat_g": 0.22,
    "carbs_g": 2.23,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld015",
    "food_code": "SLD015",
    "name": "Bottle gourd, elongate",
    "category": "Vegetable",
    "calories_per_100g": 10.0,
    "protein_g": 0.46,
    "fat_g": 0.15,
    "carbs_g": 1.64,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld016",
    "food_code": "SLD016",
    "name": "Bottle gourd, round",
    "category": "Vegetable",
    "calories_per_100g": 13.0,
    "protein_g": 0.42,
    "fat_g": 0.12,
    "carbs_g": 2.53,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld017",
    "food_code": "SLD017",
    "name": "Brinjal, Chinese eggplant",
    "category": "Vegetable",
    "calories_per_100g": 24.0,
    "protein_g": 1.28,
    "fat_g": 0.33,
    "carbs_g": 3.46,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld018",
    "food_code": "SLD018",
    "name": "Brinjal, little prince eggplant",
    "category": "Vegetable",
    "calories_per_100g": 21.0,
    "protein_g": 1.28,
    "fat_g": 0.39,
    "carbs_g": 2.64,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld019",
    "food_code": "SLD019",
    "name": "Brinjal, pandora striped",
    "category": "Vegetable",
    "calories_per_100g": 29.0,
    "protein_g": 1.49,
    "fat_g": 0.31,
    "carbs_g": 4.51,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld020",
    "food_code": "SLD020",
    "name": "Brinjal, Thai eggplant",
    "category": "Vegetable",
    "calories_per_100g": 21.0,
    "protein_g": 1.45,
    "fat_g": 0.26,
    "carbs_g": 2.6,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld021",
    "food_code": "SLD021",
    "name": "Cabbage, Chinese",
    "category": "Vegetable",
    "calories_per_100g": 17.0,
    "protein_g": 1.58,
    "fat_g": 0.13,
    "carbs_g": 2.36,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld022",
    "food_code": "SLD022",
    "name": "Cabbage, collard greens",
    "category": "Vegetable",
    "calories_per_100g": 30.0,
    "protein_g": 3.63,
    "fat_g": 0.27,
    "carbs_g": 2.79,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld023",
    "food_code": "SLD023",
    "name": "Cabbage, green",
    "category": "Vegetable",
    "calories_per_100g": 21.0,
    "protein_g": 1.35,
    "fat_g": 0.14,
    "carbs_g": 3.15,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld024",
    "food_code": "SLD024",
    "name": "Cabbage, violet",
    "category": "Vegetable",
    "calories_per_100g": 23.0,
    "protein_g": 1.51,
    "fat_g": 0.22,
    "carbs_g": 3.62,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld025",
    "food_code": "SLD025",
    "name": "Canereed leaves",
    "category": "Vegetable",
    "calories_per_100g": 33.0,
    "protein_g": 2.52,
    "fat_g": 0.52,
    "carbs_g": 4.3,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld026",
    "food_code": "SLD026",
    "name": "Capsicum, green",
    "category": "Vegetable",
    "calories_per_100g": 13.0,
    "protein_g": 1.25,
    "fat_g": 0.29,
    "carbs_g": 1.28,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld027",
    "food_code": "SLD027",
    "name": "Capsicum, local",
    "category": "Vegetable",
    "calories_per_100g": 23.0,
    "protein_g": 1.22,
    "fat_g": 0.34,
    "carbs_g": 3.59,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld028",
    "food_code": "SLD028",
    "name": "Capsicum, red",
    "category": "Vegetable",
    "calories_per_100g": 27.0,
    "protein_g": 1.83,
    "fat_g": 0.46,
    "carbs_g": 3.63,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld029",
    "food_code": "SLD029",
    "name": "Capsicum, yellow",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 1.59,
    "fat_g": 0.39,
    "carbs_g": 2.11,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld030",
    "food_code": "SLD030",
    "name": "Cassava leaves",
    "category": "Vegetable",
    "calories_per_100g": 64.0,
    "protein_g": 6.13,
    "fat_g": 1.92,
    "carbs_g": 5.37,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld031",
    "food_code": "SLD031",
    "name": "Cauliflower",
    "category": "Vegetable",
    "calories_per_100g": 23.0,
    "protein_g": 2.09,
    "fat_g": 0.48,
    "carbs_g": 2.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld032",
    "food_code": "SLD032",
    "name": "Celery stalk",
    "category": "Vegetable",
    "calories_per_100g": 15.0,
    "protein_g": 0.82,
    "fat_g": 0.2,
    "carbs_g": 2.22,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld033",
    "food_code": "SLD033",
    "name": "Cho-cho marrow",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 0.58,
    "fat_g": 0.12,
    "carbs_g": 3.73,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld034",
    "food_code": "SLD034",
    "name": "Colocasia leaves, green",
    "category": "Vegetable",
    "calories_per_100g": 39.0,
    "protein_g": 3.14,
    "fat_g": 1.42,
    "carbs_g": 2.97,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld035",
    "food_code": "SLD035",
    "name": "Colocasia, stem, black",
    "category": "Vegetable",
    "calories_per_100g": 23.0,
    "protein_g": 0.76,
    "fat_g": 0.34,
    "carbs_g": 3.83,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld036",
    "food_code": "SLD036",
    "name": "Colocasia, stem, green",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 0.91,
    "fat_g": 0.22,
    "carbs_g": 2.86,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld037",
    "food_code": "SLD037",
    "name": "Corn, baby",
    "category": "Vegetable",
    "calories_per_100g": 73.0,
    "protein_g": 2.69,
    "fat_g": 1.33,
    "carbs_g": 11.66,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld038",
    "food_code": "SLD038",
    "name": "Cucumber, Indian",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 0.98,
    "fat_g": 0.24,
    "carbs_g": 3.01,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld039",
    "food_code": "SLD039",
    "name": "Cucumber, Mangalore",
    "category": "Vegetable",
    "calories_per_100g": 17.0,
    "protein_g": 1.01,
    "fat_g": 0.25,
    "carbs_g": 2.56,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld040",
    "food_code": "SLD040",
    "name": "Cucumber, Persian",
    "category": "Vegetable",
    "calories_per_100g": 21.0,
    "protein_g": 0.77,
    "fat_g": 0.18,
    "carbs_g": 3.93,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld041",
    "food_code": "SLD041",
    "name": "Drumstick (murunga)",
    "category": "Vegetable",
    "calories_per_100g": 30.0,
    "protein_g": 2.48,
    "fat_g": 0.12,
    "carbs_g": 4.14,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld042",
    "food_code": "SLD042",
    "name": "Drumstick leaves (murunga kola)",
    "category": "Vegetable",
    "calories_per_100g": 59.0,
    "protein_g": 6.03,
    "fat_g": 1.74,
    "carbs_g": 3.96,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld043",
    "food_code": "SLD043",
    "name": "Garden cress",
    "category": "Vegetable",
    "calories_per_100g": 47.0,
    "protein_g": 5.29,
    "fat_g": 0.79,
    "carbs_g": 4.21,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld044",
    "food_code": "SLD044",
    "name": "Golden leather fern fiddlehead",
    "category": "Vegetable",
    "calories_per_100g": 31.0,
    "protein_g": 2.33,
    "fat_g": 0.34,
    "carbs_g": 4.58,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld045",
    "food_code": "SLD045",
    "name": "Green milkweed climber",
    "category": "Vegetable",
    "calories_per_100g": 58.0,
    "protein_g": 4.85,
    "fat_g": 0.69,
    "carbs_g": 7.61,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld046",
    "food_code": "SLD046",
    "name": "Horse purslane",
    "category": "Vegetable",
    "calories_per_100g": 20.0,
    "protein_g": 2.42,
    "fat_g": 0.21,
    "carbs_g": 2.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld047",
    "food_code": "SLD047",
    "name": "Hummingbird tree leaves (katuru murunga)",
    "category": "Vegetable",
    "calories_per_100g": 70.0,
    "protein_g": 8.01,
    "fat_g": 1.35,
    "carbs_g": 5.21,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld048",
    "food_code": "SLD048",
    "name": "Indian pennywort (gotukola)",
    "category": "Vegetable",
    "calories_per_100g": 15.0,
    "protein_g": 0.64,
    "fat_g": 0.47,
    "carbs_g": 1.93,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld049",
    "food_code": "SLD049",
    "name": "Jack fruit, raw",
    "category": "Vegetable",
    "calories_per_100g": 25.0,
    "protein_g": 2.14,
    "fat_g": 0.34,
    "carbs_g": 3.28,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld050",
    "food_code": "SLD050",
    "name": "Jack fruit seed, mature",
    "category": "Vegetable",
    "calories_per_100g": 77.0,
    "protein_g": 5.66,
    "fat_g": 0.44,
    "carbs_g": 12.14,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld051",
    "food_code": "SLD051",
    "name": "Knol-Khol",
    "category": "Vegetable",
    "calories_per_100g": 16.0,
    "protein_g": 1.69,
    "fat_g": 0.34,
    "carbs_g": 1.53,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld052",
    "food_code": "SLD052",
    "name": "Knol-Khol leaves",
    "category": "Vegetable",
    "calories_per_100g": 42.0,
    "protein_g": 3.12,
    "fat_g": 0.35,
    "carbs_g": 6.16,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld053",
    "food_code": "SLD053",
    "name": "Ladies finger (okra)",
    "category": "Vegetable",
    "calories_per_100g": 26.0,
    "protein_g": 2.06,
    "fat_g": 0.19,
    "carbs_g": 3.62,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld054",
    "food_code": "SLD054",
    "name": "Lasia shoots",
    "category": "Vegetable",
    "calories_per_100g": 33.0,
    "protein_g": 4.1,
    "fat_g": 0.83,
    "carbs_g": 2.03,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld055",
    "food_code": "SLD055",
    "name": "Leeks",
    "category": "Vegetable",
    "calories_per_100g": 30.0,
    "protein_g": 1.74,
    "fat_g": 0.49,
    "carbs_g": 4.64,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld056",
    "food_code": "SLD056",
    "name": "Lettuce",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 1.05,
    "fat_g": 0.24,
    "carbs_g": 3.08,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld057",
    "food_code": "SLD057",
    "name": "Malabar spinach",
    "category": "Vegetable",
    "calories_per_100g": 22.0,
    "protein_g": 2.2,
    "fat_g": 0.47,
    "carbs_g": 2.05,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld058",
    "food_code": "SLD058",
    "name": "Mango, green, raw",
    "category": "Vegetable",
    "calories_per_100g": 50.0,
    "protein_g": 0.75,
    "fat_g": 0.09,
    "carbs_g": 10.8,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld059",
    "food_code": "SLD059",
    "name": "Mushroom, Oyster, white",
    "category": "Vegetable",
    "calories_per_100g": 27.0,
    "protein_g": 2.54,
    "fat_g": 0.42,
    "carbs_g": 2.92,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld060",
    "food_code": "SLD060",
    "name": "Onion, stalk",
    "category": "Vegetable",
    "calories_per_100g": 27.0,
    "protein_g": 2.01,
    "fat_g": 0.26,
    "carbs_g": 3.37,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld061",
    "food_code": "SLD061",
    "name": "Pak Choi leaves",
    "category": "Vegetable",
    "calories_per_100g": 16.0,
    "protein_g": 1.41,
    "fat_g": 0.25,
    "carbs_g": 1.78,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld062",
    "food_code": "SLD062",
    "name": "Papaya, raw",
    "category": "Vegetable",
    "calories_per_100g": 25.0,
    "protein_g": 0.58,
    "fat_g": 0.22,
    "carbs_g": 4.78,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld063",
    "food_code": "SLD063",
    "name": "Parsley",
    "category": "Vegetable",
    "calories_per_100g": 72.0,
    "protein_g": 5.55,
    "fat_g": 1.14,
    "carbs_g": 9.43,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld064",
    "food_code": "SLD064",
    "name": "Passion fruit leaves",
    "category": "Vegetable",
    "calories_per_100g": 50.0,
    "protein_g": 5.5,
    "fat_g": 1.29,
    "carbs_g": 3.47,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld065",
    "food_code": "SLD065",
    "name": "Plantain, ash",
    "category": "Vegetable",
    "calories_per_100g": 76.0,
    "protein_g": 2.84,
    "fat_g": 0.56,
    "carbs_g": 14.75,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld066",
    "food_code": "SLD066",
    "name": "Plantain, ash, peels",
    "category": "Vegetable",
    "calories_per_100g": 34.0,
    "protein_g": 1.13,
    "fat_g": 0.69,
    "carbs_g": 5.53,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld067",
    "food_code": "SLD067",
    "name": "Plantain, flower",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 1.36,
    "fat_g": 0.63,
    "carbs_g": 1.79,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld068",
    "food_code": "SLD068",
    "name": "Plantain, green",
    "category": "Vegetable",
    "calories_per_100g": 79.0,
    "protein_g": 0.99,
    "fat_g": 0.22,
    "carbs_g": 17.71,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld069",
    "food_code": "SLD069",
    "name": "Plantain, stem",
    "category": "Vegetable",
    "calories_per_100g": 44.0,
    "protein_g": 0.3,
    "fat_g": 0.17,
    "carbs_g": 9.97,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld070",
    "food_code": "SLD070",
    "name": "Pumpkin leaves, tender",
    "category": "Vegetable",
    "calories_per_100g": 41.0,
    "protein_g": 3.85,
    "fat_g": 0.72,
    "carbs_g": 4.53,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld071",
    "food_code": "SLD071",
    "name": "Pumpkin, common",
    "category": "Vegetable",
    "calories_per_100g": 31.0,
    "protein_g": 0.86,
    "fat_g": 0.3,
    "carbs_g": 5.82,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld072",
    "food_code": "SLD072",
    "name": "Pumpkin, green, cylindrical",
    "category": "Vegetable",
    "calories_per_100g": 24.0,
    "protein_g": 0.87,
    "fat_g": 0.18,
    "carbs_g": 4.22,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld073",
    "food_code": "SLD073",
    "name": "Pumpkin, orange, round",
    "category": "Vegetable",
    "calories_per_100g": 21.0,
    "protein_g": 0.95,
    "fat_g": 0.16,
    "carbs_g": 3.33,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld074",
    "food_code": "SLD074",
    "name": "Radish leaves",
    "category": "Vegetable",
    "calories_per_100g": 27.0,
    "protein_g": 2.23,
    "fat_g": 0.56,
    "carbs_g": 3.14,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld075",
    "food_code": "SLD075",
    "name": "Ridge gourd",
    "category": "Vegetable",
    "calories_per_100g": 12.0,
    "protein_g": 0.86,
    "fat_g": 0.15,
    "carbs_g": 1.63,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld076",
    "food_code": "SLD076",
    "name": "Sessile joyweed",
    "category": "Vegetable",
    "calories_per_100g": 28.0,
    "protein_g": 3.15,
    "fat_g": 0.55,
    "carbs_g": 2.34,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld077",
    "food_code": "SLD077",
    "name": "Snake gourd, dark green",
    "category": "Vegetable",
    "calories_per_100g": 11.0,
    "protein_g": 0.89,
    "fat_g": 0.25,
    "carbs_g": 1.23,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld078",
    "food_code": "SLD078",
    "name": "Snake gourd, pale green",
    "category": "Vegetable",
    "calories_per_100g": 11.0,
    "protein_g": 0.82,
    "fat_g": 0.25,
    "carbs_g": 1.25,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld079",
    "food_code": "SLD079",
    "name": "Spiny gourd",
    "category": "Vegetable",
    "calories_per_100g": 47.0,
    "protein_g": 2.13,
    "fat_g": 0.5,
    "carbs_g": 8.46,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld080",
    "food_code": "SLD080",
    "name": "Sweet leaf (mukunuwenna)",
    "category": "Vegetable",
    "calories_per_100g": 71.0,
    "protein_g": 7.53,
    "fat_g": 2.19,
    "carbs_g": 5.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld081",
    "food_code": "SLD081",
    "name": "Tamarind leaves, tender",
    "category": "Vegetable",
    "calories_per_100g": 71.0,
    "protein_g": 5.84,
    "fat_g": 0.49,
    "carbs_g": 10.04,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld082",
    "food_code": "SLD082",
    "name": "Tomato, green",
    "category": "Vegetable",
    "calories_per_100g": 19.0,
    "protein_g": 1.13,
    "fat_g": 0.24,
    "carbs_g": 2.94,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld083",
    "food_code": "SLD083",
    "name": "Tomato, ripe, hybrid",
    "category": "Vegetable",
    "calories_per_100g": 16.0,
    "protein_g": 0.7,
    "fat_g": 0.24,
    "carbs_g": 2.78,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld084",
    "food_code": "SLD084",
    "name": "Tomato, ripe, local",
    "category": "Vegetable",
    "calories_per_100g": 20.0,
    "protein_g": 0.88,
    "fat_g": 0.56,
    "carbs_g": 2.74,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld085",
    "food_code": "SLD085",
    "name": "Turkey berry (thiththa)",
    "category": "Vegetable",
    "calories_per_100g": 61.0,
    "protein_g": 1.66,
    "fat_g": 1.96,
    "carbs_g": 8.54,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld086",
    "food_code": "SLD086",
    "name": "Water spinach (kankun)",
    "category": "Vegetable",
    "calories_per_100g": 15.0,
    "protein_g": 0.47,
    "fat_g": 0.37,
    "carbs_g": 2.43,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld087",
    "food_code": "SLD087",
    "name": "Wing bean",
    "category": "Vegetable",
    "calories_per_100g": 21.0,
    "protein_g": 1.84,
    "fat_g": 0.2,
    "carbs_g": 2.76,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld088",
    "food_code": "SLD088",
    "name": "Zucchini, green",
    "category": "Vegetable",
    "calories_per_100g": 20.0,
    "protein_g": 1.1,
    "fat_g": 0.51,
    "carbs_g": 2.33,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sld089",
    "food_code": "SLD089",
    "name": "Zucchini, yellow",
    "category": "Vegetable",
    "calories_per_100g": 18.0,
    "protein_g": 1.31,
    "fat_g": 0.44,
    "carbs_g": 2.2,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla001",
    "food_code": "SLA001",
    "name": "Barley",
    "category": "Cereal",
    "calories_per_100g": 313.0,
    "protein_g": 11.4,
    "fat_g": 1.18,
    "carbs_g": 60.9,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla002",
    "food_code": "SLA002",
    "name": "Maize, dry, local",
    "category": "Cereal",
    "calories_per_100g": 338.0,
    "protein_g": 8.47,
    "fat_g": 4.58,
    "carbs_g": 64.43,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla003",
    "food_code": "SLA003",
    "name": "Maize, tender, local",
    "category": "Cereal",
    "calories_per_100g": 119.0,
    "protein_g": 3.01,
    "fat_g": 1.23,
    "carbs_g": 23.54,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla004",
    "food_code": "SLA004",
    "name": "Maize, tender, sweet",
    "category": "Cereal",
    "calories_per_100g": 94.0,
    "protein_g": 3.86,
    "fat_g": 1.43,
    "carbs_g": 15.92,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla005",
    "food_code": "SLA005",
    "name": "Millet, finger (kurakkan)",
    "category": "Cereal",
    "calories_per_100g": 322.0,
    "protein_g": 7.11,
    "fat_g": 1.77,
    "carbs_g": 67.45,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla006",
    "food_code": "SLA006",
    "name": "Rice, flakes (petti)",
    "category": "Cereal",
    "calories_per_100g": 350.0,
    "protein_g": 7.29,
    "fat_g": 1.17,
    "carbs_g": 76.08,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla007",
    "food_code": "SLA007",
    "name": "Rice, kaluhinati",
    "category": "Cereal",
    "calories_per_100g": 348.0,
    "protein_g": 9.88,
    "fat_g": 1.9,
    "carbs_g": 72.28,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla008",
    "food_code": "SLA008",
    "name": "Rice, keeri samba",
    "category": "Cereal",
    "calories_per_100g": 368.0,
    "protein_g": 8.47,
    "fat_g": 1.84,
    "carbs_g": 79.41,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla009",
    "food_code": "SLA009",
    "name": "Rice, kekulu, red",
    "category": "Cereal",
    "calories_per_100g": 366.0,
    "protein_g": 8.64,
    "fat_g": 2.12,
    "carbs_g": 77.59,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla010",
    "food_code": "SLA010",
    "name": "Rice, kekulu, white",
    "category": "Cereal",
    "calories_per_100g": 361.0,
    "protein_g": 9.88,
    "fat_g": 1.52,
    "carbs_g": 76.67,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla011",
    "food_code": "SLA011",
    "name": "Rice, nadu, white",
    "category": "Cereal",
    "calories_per_100g": 366.0,
    "protein_g": 7.76,
    "fat_g": 1.48,
    "carbs_g": 80.11,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla012",
    "food_code": "SLA012",
    "name": "Rice, samba",
    "category": "Cereal",
    "calories_per_100g": 369.0,
    "protein_g": 6.86,
    "fat_g": 2.45,
    "carbs_g": 79.53,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla013",
    "food_code": "SLA013",
    "name": "Rice, samba kekulu",
    "category": "Cereal",
    "calories_per_100g": 355.0,
    "protein_g": 8.81,
    "fat_g": 1.53,
    "carbs_g": 76.12,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla014",
    "food_code": "SLA014",
    "name": "Vermicelli, rice",
    "category": "Cereal",
    "calories_per_100g": 365.0,
    "protein_g": 7.29,
    "fat_g": 1.13,
    "carbs_g": 80.97,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla015",
    "food_code": "SLA015",
    "name": "Vermicelli, wheat",
    "category": "Cereal",
    "calories_per_100g": 332.0,
    "protein_g": 9.31,
    "fat_g": 0.42,
    "carbs_g": 70.69,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla016",
    "food_code": "SLA016",
    "name": "Water lily seeds",
    "category": "Cereal",
    "calories_per_100g": 349.0,
    "protein_g": 9.84,
    "fat_g": 2.22,
    "carbs_g": 71.89,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla017",
    "food_code": "SLA017",
    "name": "Wheat flour, atta",
    "category": "Cereal",
    "calories_per_100g": 319.0,
    "protein_g": 10.25,
    "fat_g": 1.4,
    "carbs_g": 64.19,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla018",
    "food_code": "SLA018",
    "name": "Wheat flour, refined",
    "category": "Cereal",
    "calories_per_100g": 355.0,
    "protein_g": 10.42,
    "fat_g": 0.73,
    "carbs_g": 75.25,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sla019",
    "food_code": "SLA019",
    "name": "Wheat, semolina",
    "category": "Cereal",
    "calories_per_100g": 332.0,
    "protein_g": 10.85,
    "fat_g": 0.72,
    "carbs_g": 68.83,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc001",
    "food_code": "SLC001",
    "name": "Bengal gram dhal (kadala)",
    "category": "Legume",
    "calories_per_100g": 327.0,
    "protein_g": 20.12,
    "fat_g": 5.32,
    "carbs_g": 47.88,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc002",
    "food_code": "SLC002",
    "name": "Bengal gram, whole",
    "category": "Legume",
    "calories_per_100g": 288.0,
    "protein_g": 18.68,
    "fat_g": 5.01,
    "carbs_g": 39.69,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc003",
    "food_code": "SLC003",
    "name": "Black gram dhal (ulundu)",
    "category": "Legume",
    "calories_per_100g": 323.0,
    "protein_g": 22.43,
    "fat_g": 1.69,
    "carbs_g": 51.61,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc004",
    "food_code": "SLC004",
    "name": "Cowpea, brown",
    "category": "Legume",
    "calories_per_100g": 320.0,
    "protein_g": 20.24,
    "fat_g": 1.08,
    "carbs_g": 54.96,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc005",
    "food_code": "SLC005",
    "name": "Cowpea, white",
    "category": "Legume",
    "calories_per_100g": 320.0,
    "protein_g": 21.25,
    "fat_g": 1.14,
    "carbs_g": 53.77,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc006",
    "food_code": "SLC006",
    "name": "Green gram dhal (mung dhal)",
    "category": "Legume",
    "calories_per_100g": 326.0,
    "protein_g": 23.4,
    "fat_g": 1.39,
    "carbs_g": 53.31,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc007",
    "food_code": "SLC007",
    "name": "Green gram, whole (mung)",
    "category": "Legume",
    "calories_per_100g": 290.0,
    "protein_g": 21.97,
    "fat_g": 0.93,
    "carbs_g": 46.57,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc008",
    "food_code": "SLC008",
    "name": "Horse gram, whole",
    "category": "Legume",
    "calories_per_100g": 328.0,
    "protein_g": 21.27,
    "fat_g": 0.64,
    "carbs_g": 57.35,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc009",
    "food_code": "SLC009",
    "name": "Lentil, dhal (parippu)",
    "category": "Legume",
    "calories_per_100g": 319.0,
    "protein_g": 23.09,
    "fat_g": 0.77,
    "carbs_g": 53.08,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slc010",
    "food_code": "SLC010",
    "name": "Peas, dry",
    "category": "Legume",
    "calories_per_100g": 299.0,
    "protein_g": 19.18,
    "fat_g": 1.85,
    "carbs_g": 49.44,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sll001",
    "food_code": "SLL001",
    "name": "Coconut water, green, immature",
    "category": "Beverage",
    "calories_per_100g": 20,
    "protein_g": 0.6,
    "fat_g": 0.3,
    "carbs_g": 3.2,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sll002",
    "food_code": "SLL002",
    "name": "Coconut water, orange (king coconut)",
    "category": "Beverage",
    "calories_per_100g": 4,
    "protein_g": 0.29,
    "fat_g": 0.0,
    "carbs_g": 0.71,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk001",
    "food_code": "SLK001",
    "name": "Cardamom",
    "category": "Spice",
    "calories_per_100g": 260,
    "protein_g": 8.25,
    "fat_g": 2.75,
    "carbs_g": 48.59,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk002",
    "food_code": "SLK002",
    "name": "Chillies, dark green, short",
    "category": "Spice",
    "calories_per_100g": 39,
    "protein_g": 2.28,
    "fat_g": 0.76,
    "carbs_g": 5.25,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk003",
    "food_code": "SLK003",
    "name": "Chillies, yellowish green, long",
    "category": "Spice",
    "calories_per_100g": 44,
    "protein_g": 2.21,
    "fat_g": 0.75,
    "carbs_g": 6.26,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk004",
    "food_code": "SLK004",
    "name": "Chillies, red, dry",
    "category": "Spice",
    "calories_per_100g": 233,
    "protein_g": 12.68,
    "fat_g": 6.41,
    "carbs_g": 28.73,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk005",
    "food_code": "SLK005",
    "name": "Cloves",
    "category": "Spice",
    "calories_per_100g": 187,
    "protein_g": 6.04,
    "fat_g": 8.45,
    "carbs_g": 18.73,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk006",
    "food_code": "SLK006",
    "name": "Coriander seeds",
    "category": "Spice",
    "calories_per_100g": 257,
    "protein_g": 10.38,
    "fat_g": 17.21,
    "carbs_g": 10.43,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk007",
    "food_code": "SLK007",
    "name": "Coriander, leaves",
    "category": "Spice",
    "calories_per_100g": 31,
    "protein_g": 3.27,
    "fat_g": 0.71,
    "carbs_g": 2.25,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk008",
    "food_code": "SLK008",
    "name": "Cumin seeds",
    "category": "Spice",
    "calories_per_100g": 298,
    "protein_g": 13.43,
    "fat_g": 16.66,
    "carbs_g": 21.46,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk009",
    "food_code": "SLK009",
    "name": "Curry leaves",
    "category": "Spice",
    "calories_per_100g": 58,
    "protein_g": 7.19,
    "fat_g": 1.04,
    "carbs_g": 3.01,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk010",
    "food_code": "SLK010",
    "name": "Fenugreek seeds (uluhal)",
    "category": "Spice",
    "calories_per_100g": 235,
    "protein_g": 25.05,
    "fat_g": 5.73,
    "carbs_g": 11.05,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk011",
    "food_code": "SLK011",
    "name": "Garlic",
    "category": "Spice",
    "calories_per_100g": 122,
    "protein_g": 6.76,
    "fat_g": 0.14,
    "carbs_g": 21.75,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk012",
    "food_code": "SLK012",
    "name": "Ginger fresh, large",
    "category": "Spice",
    "calories_per_100g": 56,
    "protein_g": 2.23,
    "fat_g": 0.81,
    "carbs_g": 9.43,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk013",
    "food_code": "SLK013",
    "name": "Ginger fresh, small",
    "category": "Spice",
    "calories_per_100g": 41,
    "protein_g": 1.22,
    "fat_g": 0.67,
    "carbs_g": 7.08,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk014",
    "food_code": "SLK014",
    "name": "Mint leaves",
    "category": "Spice",
    "calories_per_100g": 37,
    "protein_g": 4.72,
    "fat_g": 0.7,
    "carbs_g": 2.32,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk015",
    "food_code": "SLK015",
    "name": "Nutmeg",
    "category": "Spice",
    "calories_per_100g": 466,
    "protein_g": 6.08,
    "fat_g": 36.55,
    "carbs_g": 28.54,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk016",
    "food_code": "SLK016",
    "name": "Onion, big",
    "category": "Spice",
    "calories_per_100g": 48,
    "protein_g": 1.67,
    "fat_g": 0.24,
    "carbs_g": 9.54,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk017",
    "food_code": "SLK017",
    "name": "Onion, small, shallots",
    "category": "Spice",
    "calories_per_100g": 55,
    "protein_g": 2.13,
    "fat_g": 0.15,
    "carbs_g": 11.05,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk018",
    "food_code": "SLK018",
    "name": "Pepper, black",
    "category": "Spice",
    "calories_per_100g": 218,
    "protein_g": 10.17,
    "fat_g": 2.76,
    "carbs_g": 36.35,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slk019",
    "food_code": "SLK019",
    "name": "Turmeric powder",
    "category": "Spice",
    "calories_per_100g": 281,
    "protein_g": 7.46,
    "fat_g": 5.04,
    "carbs_g": 49.65,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj001",
    "food_code": "SLJ001",
    "name": "Canola oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj002",
    "food_code": "SLJ002",
    "name": "Coconut oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj003",
    "food_code": "SLJ003",
    "name": "Corn oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj004",
    "food_code": "SLJ004",
    "name": "Margarine",
    "category": "Oil",
    "calories_per_100g": 750,
    "protein_g": 0.3,
    "fat_g": 83.3,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj005",
    "food_code": "SLJ005",
    "name": "Mustard seed oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj006",
    "food_code": "SLJ006",
    "name": "Olive oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj007",
    "food_code": "SLJ007",
    "name": "Palm Olein",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj008",
    "food_code": "SLJ008",
    "name": "Peanut oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj009",
    "food_code": "SLJ009",
    "name": "Rice bran oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj010",
    "food_code": "SLJ010",
    "name": "Sesame oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj011",
    "food_code": "SLJ011",
    "name": "Soy bean oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slj012",
    "food_code": "SLJ012",
    "name": "Sunflower oil",
    "category": "Oil",
    "calories_per_100g": 900,
    "protein_g": 0.0,
    "fat_g": 100.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli001",
    "food_code": "SLI001",
    "name": "Almond",
    "category": "Nut/Seed",
    "calories_per_100g": 607,
    "protein_g": 18.45,
    "fat_g": 58.51,
    "carbs_g": 2.66,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli002",
    "food_code": "SLI002",
    "name": "Arecanut, dried, brown",
    "category": "Nut/Seed",
    "calories_per_100g": 348,
    "protein_g": 6.39,
    "fat_g": 4.31,
    "carbs_g": 69.47,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli003",
    "food_code": "SLI003",
    "name": "Arecanut, fresh",
    "category": "Nut/Seed",
    "calories_per_100g": 242,
    "protein_g": 3.03,
    "fat_g": 5.18,
    "carbs_g": 44.55,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli004",
    "food_code": "SLI004",
    "name": "Cashew nut",
    "category": "Nut/Seed",
    "calories_per_100g": 580,
    "protein_g": 18.47,
    "fat_g": 45.16,
    "carbs_g": 25.14,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli005",
    "food_code": "SLI005",
    "name": "Coconut, kernel, dry",
    "category": "Nut/Seed",
    "calories_per_100g": 626,
    "protein_g": 7.29,
    "fat_g": 63.19,
    "carbs_g": 8.95,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli006",
    "food_code": "SLI006",
    "name": "Coconut, kernel, fresh, scraped",
    "category": "Nut/Seed",
    "calories_per_100g": 390,
    "protein_g": 3.67,
    "fat_g": 39.92,
    "carbs_g": 3.41,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli007",
    "food_code": "SLI007",
    "name": "Gingely seeds, black (thala)",
    "category": "Nut/Seed",
    "calories_per_100g": 509,
    "protein_g": 19.65,
    "fat_g": 43.11,
    "carbs_g": 10.22,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli008",
    "food_code": "SLI008",
    "name": "Gingely seeds, brown (thala)",
    "category": "Nut/Seed",
    "calories_per_100g": 517,
    "protein_g": 21.96,
    "fat_g": 43.27,
    "carbs_g": 9.56,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli009",
    "food_code": "SLI009",
    "name": "Ground nut (peanut)",
    "category": "Nut/Seed",
    "calories_per_100g": 517,
    "protein_g": 22.43,
    "fat_g": 39.88,
    "carbs_g": 17.32,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli010",
    "food_code": "SLI010",
    "name": "Linseeds",
    "category": "Nut/Seed",
    "calories_per_100g": 440,
    "protein_g": 18.7,
    "fat_g": 35.12,
    "carbs_g": 11.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli011",
    "food_code": "SLI011",
    "name": "Mustard seeds",
    "category": "Nut/Seed",
    "calories_per_100g": 508,
    "protein_g": 19.57,
    "fat_g": 40.06,
    "carbs_g": 16.85,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli012",
    "food_code": "SLI012",
    "name": "Pistachio nut",
    "category": "Nut/Seed",
    "calories_per_100g": 541,
    "protein_g": 23.64,
    "fat_g": 42.95,
    "carbs_g": 15.06,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli013",
    "food_code": "SLI013",
    "name": "Tropical Almond (kottamba)",
    "category": "Nut/Seed",
    "calories_per_100g": 458,
    "protein_g": 17.14,
    "fat_g": 41.28,
    "carbs_g": 3.2,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "sli014",
    "food_code": "SLI014",
    "name": "Walnut",
    "category": "Nut/Seed",
    "calories_per_100g": 671,
    "protein_g": 14.6,
    "fat_g": 64.31,
    "carbs_g": 10.49,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh001",
    "food_code": "SLH001",
    "name": "Egg, country, whole, raw",
    "category": "Egg",
    "calories_per_100g": 170,
    "protein_g": 13.14,
    "fat_g": 13.0,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh002",
    "food_code": "SLH002",
    "name": "Egg, table, white, raw",
    "category": "Egg",
    "calories_per_100g": 43,
    "protein_g": 10.71,
    "fat_g": 0.06,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh003",
    "food_code": "SLH003",
    "name": "Egg, table, whole, raw",
    "category": "Egg",
    "calories_per_100g": 135,
    "protein_g": 13.55,
    "fat_g": 9.03,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh004",
    "food_code": "SLH004",
    "name": "Egg, table, yolk, raw",
    "category": "Egg",
    "calories_per_100g": 299,
    "protein_g": 15.85,
    "fat_g": 26.22,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh005",
    "food_code": "SLH005",
    "name": "Egg, quail, whole, raw",
    "category": "Egg",
    "calories_per_100g": 153,
    "protein_g": 12.39,
    "fat_g": 11.46,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh006",
    "food_code": "SLH006",
    "name": "Chicken, Broiler, breast, skinless",
    "category": "Poultry",
    "calories_per_100g": 176,
    "protein_g": 23.14,
    "fat_g": 9.24,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh007",
    "food_code": "SLH007",
    "name": "Chicken, Broiler, gizzard",
    "category": "Poultry",
    "calories_per_100g": 91,
    "protein_g": 18.22,
    "fat_g": 2.07,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh008",
    "food_code": "SLH008",
    "name": "Chicken, Broiler, drumstick, skinless",
    "category": "Poultry",
    "calories_per_100g": 186,
    "protein_g": 18.57,
    "fat_g": 12.45,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh009",
    "food_code": "SLH009",
    "name": "Chicken, Broiler, liver",
    "category": "Poultry",
    "calories_per_100g": 123,
    "protein_g": 21.57,
    "fat_g": 4.08,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh010",
    "food_code": "SLH010",
    "name": "Chicken, Broiler, thigh, skinless",
    "category": "Poultry",
    "calories_per_100g": 211,
    "protein_g": 18.61,
    "fat_g": 15.15,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh011",
    "food_code": "SLH011",
    "name": "Chicken, country, breast, with skin",
    "category": "Poultry",
    "calories_per_100g": 180,
    "protein_g": 22.08,
    "fat_g": 10.2,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh012",
    "food_code": "SLH012",
    "name": "Chicken, country, leg, with skin",
    "category": "Poultry",
    "calories_per_100g": 174,
    "protein_g": 17.01,
    "fat_g": 11.73,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh013",
    "food_code": "SLH013",
    "name": "Chicken, country, thigh, with skin",
    "category": "Poultry",
    "calories_per_100g": 189,
    "protein_g": 18.29,
    "fat_g": 12.82,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh014",
    "food_code": "SLH014",
    "name": "Chicken, country, wing, with skin",
    "category": "Poultry",
    "calories_per_100g": 183,
    "protein_g": 18.65,
    "fat_g": 12.09,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh015",
    "food_code": "SLH015",
    "name": "Turkey, breast, with skin",
    "category": "Poultry",
    "calories_per_100g": 160,
    "protein_g": 21.96,
    "fat_g": 8.04,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh016",
    "food_code": "SLH016",
    "name": "Beef, chops",
    "category": "Meat",
    "calories_per_100g": 160,
    "protein_g": 23.3,
    "fat_g": 7.45,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh017",
    "food_code": "SLH017",
    "name": "Beef, liver",
    "category": "Meat",
    "calories_per_100g": 112,
    "protein_g": 20.08,
    "fat_g": 3.54,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh018",
    "food_code": "SLH018",
    "name": "Goat, chops",
    "category": "Meat",
    "calories_per_100g": 138,
    "protein_g": 20.37,
    "fat_g": 6.23,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slh019",
    "food_code": "SLH019",
    "name": "Pork, shoulder",
    "category": "Meat",
    "calories_per_100g": 161,
    "protein_g": 18.83,
    "fat_g": 9.5,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg001",
    "food_code": "SLG001",
    "name": "Butter, Salted",
    "category": "Dairy",
    "calories_per_100g": 733,
    "protein_g": 0.9,
    "fat_g": 81.0,
    "carbs_g": 0.2,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg002",
    "food_code": "SLG002",
    "name": "Cheese, cheddar, regular fat",
    "category": "Dairy",
    "calories_per_100g": 380,
    "protein_g": 19.75,
    "fat_g": 28.27,
    "carbs_g": 11.67,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg003",
    "food_code": "SLG003",
    "name": "Cheese, cottage, paneer",
    "category": "Dairy",
    "calories_per_100g": 346,
    "protein_g": 24.6,
    "fat_g": 25.1,
    "carbs_g": 5.4,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg004",
    "food_code": "SLG004",
    "name": "Curd, buffalo, whole",
    "category": "Dairy",
    "calories_per_100g": 99,
    "protein_g": 6.32,
    "fat_g": 6.55,
    "carbs_g": 3.86,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg005",
    "food_code": "SLG005",
    "name": "Ghee, Cow",
    "category": "Dairy",
    "calories_per_100g": 898,
    "protein_g": 0.0,
    "fat_g": 99.8,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg006",
    "food_code": "SLG006",
    "name": "Milk, cow, condensed, sweetened",
    "category": "Dairy",
    "calories_per_100g": 334,
    "protein_g": 8.2,
    "fat_g": 9.4,
    "carbs_g": 54.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg007",
    "food_code": "SLG007",
    "name": "Milk, cow, full cream",
    "category": "Dairy",
    "calories_per_100g": 63,
    "protein_g": 3.1,
    "fat_g": 3.7,
    "carbs_g": 4.3,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg008",
    "food_code": "SLG008",
    "name": "Milk, cow, low fat",
    "category": "Dairy",
    "calories_per_100g": 52,
    "protein_g": 3.71,
    "fat_g": 1.31,
    "carbs_g": 6.27,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg009",
    "food_code": "SLG009",
    "name": "Milk, cow, non-fat",
    "category": "Dairy",
    "calories_per_100g": 30,
    "protein_g": 3.1,
    "fat_g": 0.1,
    "carbs_g": 4.1,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg010",
    "food_code": "SLG010",
    "name": "Milk, cow, powdered, skimmed",
    "category": "Dairy",
    "calories_per_100g": 358,
    "protein_g": 37.6,
    "fat_g": 1.0,
    "carbs_g": 49.8,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg011",
    "food_code": "SLG011",
    "name": "Milk, cow, powdered, whole",
    "category": "Dairy",
    "calories_per_100g": 497,
    "protein_g": 26.6,
    "fat_g": 26.7,
    "carbs_g": 37.5,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg012",
    "food_code": "SLG012",
    "name": "Milk, goat, whole",
    "category": "Dairy",
    "calories_per_100g": 68,
    "protein_g": 3.5,
    "fat_g": 4.1,
    "carbs_g": 4.2,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg013",
    "food_code": "SLG013",
    "name": "Yoghurt, low fat, plain",
    "category": "Dairy",
    "calories_per_100g": 73,
    "protein_g": 9.95,
    "fat_g": 1.92,
    "carbs_g": 3.94,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slg014",
    "food_code": "SLG014",
    "name": "Yoghurt, whole",
    "category": "Dairy",
    "calories_per_100g": 94,
    "protein_g": 4.51,
    "fat_g": 3.04,
    "carbs_g": 12.03,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf001",
    "food_code": "SLF001",
    "name": "Anchovy (fresh)",
    "category": "Fish",
    "calories_per_100g": 87,
    "protein_g": 19.88,
    "fat_g": 0.78,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf002",
    "food_code": "SLF002",
    "name": "Asian Seabass",
    "category": "Fish",
    "calories_per_100g": 67,
    "protein_g": 15.28,
    "fat_g": 0.29,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf003",
    "food_code": "SLF003",
    "name": "Barracuda, Pickhandle",
    "category": "Fish",
    "calories_per_100g": 107,
    "protein_g": 22.46,
    "fat_g": 1.74,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf004",
    "food_code": "SLF004",
    "name": "Cat fish, marine",
    "category": "Fish",
    "calories_per_100g": 109,
    "protein_g": 22.18,
    "fat_g": 2.13,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf005",
    "food_code": "SLF005",
    "name": "Cobia",
    "category": "Fish",
    "calories_per_100g": 97,
    "protein_g": 20.21,
    "fat_g": 1.68,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf006",
    "food_code": "SLF006",
    "name": "Emperor fish, Spangled",
    "category": "Fish",
    "calories_per_100g": 108,
    "protein_g": 22.45,
    "fat_g": 1.92,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf007",
    "food_code": "SLF007",
    "name": "Green chromide",
    "category": "Fish",
    "calories_per_100g": 92,
    "protein_g": 19.68,
    "fat_g": 1.38,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf008",
    "food_code": "SLF008",
    "name": "Grouper",
    "category": "Fish",
    "calories_per_100g": 89,
    "protein_g": 19.38,
    "fat_g": 1.2,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf009",
    "food_code": "SLF009",
    "name": "Hairtail fish",
    "category": "Fish",
    "calories_per_100g": 128,
    "protein_g": 21.95,
    "fat_g": 4.44,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf010",
    "food_code": "SLF010",
    "name": "Indian mackerel",
    "category": "Fish",
    "calories_per_100g": 101,
    "protein_g": 21.51,
    "fat_g": 1.53,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf011",
    "food_code": "SLF011",
    "name": "Leatherjacket fish",
    "category": "Fish",
    "calories_per_100g": 75,
    "protein_g": 17.17,
    "fat_g": 0.67,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf012",
    "food_code": "SLF012",
    "name": "Mahi-mahi",
    "category": "Fish",
    "calories_per_100g": 101,
    "protein_g": 22.05,
    "fat_g": 1.33,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf013",
    "food_code": "SLF013",
    "name": "Marlin (fresh)",
    "category": "Fish",
    "calories_per_100g": 97,
    "protein_g": 22.89,
    "fat_g": 0.56,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf014",
    "food_code": "SLF014",
    "name": "Mauve-lip thread fin bream",
    "category": "Fish",
    "calories_per_100g": 126,
    "protein_g": 22.07,
    "fat_g": 4.2,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf015",
    "food_code": "SLF015",
    "name": "Pomfret, Black",
    "category": "Fish",
    "calories_per_100g": 104,
    "protein_g": 21.6,
    "fat_g": 1.8,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf016",
    "food_code": "SLF016",
    "name": "Rainbow runner",
    "category": "Fish",
    "calories_per_100g": 87,
    "protein_g": 20.02,
    "fat_g": 0.7,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf017",
    "food_code": "SLF017",
    "name": "Ray, Shortfin devil",
    "category": "Fish",
    "calories_per_100g": 98,
    "protein_g": 23.07,
    "fat_g": 0.56,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf018",
    "food_code": "SLF018",
    "name": "Ray, Stingray",
    "category": "Fish",
    "calories_per_100g": 97,
    "protein_g": 23.98,
    "fat_g": 0.68,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf019",
    "food_code": "SLF019",
    "name": "Sailfish, Indo-Pacific",
    "category": "Fish",
    "calories_per_100g": 91,
    "protein_g": 16.04,
    "fat_g": 2.88,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf020",
    "food_code": "SLF020",
    "name": "Sardinella, Goldstripe",
    "category": "Fish",
    "calories_per_100g": 100,
    "protein_g": 19.5,
    "fat_g": 2.39,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf021",
    "food_code": "SLF021",
    "name": "Sardinella, spotted",
    "category": "Fish",
    "calories_per_100g": 88,
    "protein_g": 17.08,
    "fat_g": 2.18,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf022",
    "food_code": "SLF022",
    "name": "Sardinella, White",
    "category": "Fish",
    "calories_per_100g": 152,
    "protein_g": 17.91,
    "fat_g": 8.99,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf023",
    "food_code": "SLF023",
    "name": "Scad, mackerel",
    "category": "Fish",
    "calories_per_100g": 112,
    "protein_g": 20.3,
    "fat_g": 3.37,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf024",
    "food_code": "SLF024",
    "name": "Scad, yellow-stripe",
    "category": "Fish",
    "calories_per_100g": 86,
    "protein_g": 15.69,
    "fat_g": 2.67,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf025",
    "food_code": "SLF025",
    "name": "Seer fish (thora)",
    "category": "Fish",
    "calories_per_100g": 136,
    "protein_g": 22.28,
    "fat_g": 5.18,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf026",
    "food_code": "SLF026",
    "name": "Shark, great Hammerhead",
    "category": "Fish",
    "calories_per_100g": 103,
    "protein_g": 23.4,
    "fat_g": 0.8,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf027",
    "food_code": "SLF027",
    "name": "Shark, Silky",
    "category": "Fish",
    "calories_per_100g": 95,
    "protein_g": 21.6,
    "fat_g": 0.83,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf028",
    "food_code": "SLF028",
    "name": "Swordfish",
    "category": "Fish",
    "calories_per_100g": 88,
    "protein_g": 19.82,
    "fat_g": 0.88,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf029",
    "food_code": "SLF029",
    "name": "Trevally, Blacktip",
    "category": "Fish",
    "calories_per_100g": 104,
    "protein_g": 21.58,
    "fat_g": 1.84,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf030",
    "food_code": "SLF030",
    "name": "Trevally, Diamond",
    "category": "Fish",
    "calories_per_100g": 101,
    "protein_g": 22.09,
    "fat_g": 1.27,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf031",
    "food_code": "SLF031",
    "name": "Trevally, giant",
    "category": "Fish",
    "calories_per_100g": 104,
    "protein_g": 21.87,
    "fat_g": 1.68,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf032",
    "food_code": "SLF032",
    "name": "Trevally, Bigeye",
    "category": "Fish",
    "calories_per_100g": 103,
    "protein_g": 21.95,
    "fat_g": 1.6,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf033",
    "food_code": "SLF033",
    "name": "Triggerfish",
    "category": "Fish",
    "calories_per_100g": 86,
    "protein_g": 19.7,
    "fat_g": 0.69,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf034",
    "food_code": "SLF034",
    "name": "Tuna, Frigate",
    "category": "Fish",
    "calories_per_100g": 104,
    "protein_g": 17.88,
    "fat_g": 3.38,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf035",
    "food_code": "SLF035",
    "name": "Tuna, Mackerel",
    "category": "Fish",
    "calories_per_100g": 112,
    "protein_g": 24.5,
    "fat_g": 1.44,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf036",
    "food_code": "SLF036",
    "name": "Tuna, Skipjack (fresh)",
    "category": "Fish",
    "calories_per_100g": 96,
    "protein_g": 21.28,
    "fat_g": 1.12,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf037",
    "food_code": "SLF037",
    "name": "Tuna, Yellowfin",
    "category": "Fish",
    "calories_per_100g": 109,
    "protein_g": 21.47,
    "fat_g": 2.55,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf038",
    "food_code": "SLF038",
    "name": "Wolf-herring",
    "category": "Fish",
    "calories_per_100g": 97,
    "protein_g": 21.8,
    "fat_g": 1.06,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf039",
    "food_code": "SLF039",
    "name": "Squid, hardshell",
    "category": "Seafood",
    "calories_per_100g": 76,
    "protein_g": 16.82,
    "fat_g": 0.93,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf040",
    "food_code": "SLF040",
    "name": "Squid, Long barrel",
    "category": "Seafood",
    "calories_per_100g": 84,
    "protein_g": 17.41,
    "fat_g": 1.15,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf041",
    "food_code": "SLF041",
    "name": "Squid, red",
    "category": "Seafood",
    "calories_per_100g": 78,
    "protein_g": 16.25,
    "fat_g": 1.44,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf042",
    "food_code": "SLF042",
    "name": "Octopus",
    "category": "Seafood",
    "calories_per_100g": 79,
    "protein_g": 14.71,
    "fat_g": 1.12,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf043",
    "food_code": "SLF043",
    "name": "Prawn, green tiger",
    "category": "Seafood",
    "calories_per_100g": 65,
    "protein_g": 14.85,
    "fat_g": 0.56,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf044",
    "food_code": "SLF044",
    "name": "Prawn, giant tiger",
    "category": "Seafood",
    "calories_per_100g": 64,
    "protein_g": 14.25,
    "fat_g": 0.74,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf045",
    "food_code": "SLF045",
    "name": "Crab, mud",
    "category": "Seafood",
    "calories_per_100g": 45,
    "protein_g": 10.0,
    "fat_g": 0.55,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf046",
    "food_code": "SLF046",
    "name": "Crab, Three-spot",
    "category": "Seafood",
    "calories_per_100g": 67,
    "protein_g": 15.36,
    "fat_g": 0.6,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf047",
    "food_code": "SLF047",
    "name": "Clam, white shell",
    "category": "Seafood",
    "calories_per_100g": 59,
    "protein_g": 11.82,
    "fat_g": 1.34,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf048",
    "food_code": "SLF048",
    "name": "Cat fish, freshwater",
    "category": "Fish",
    "calories_per_100g": 124,
    "protein_g": 15.86,
    "fat_g": 6.24,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf049",
    "food_code": "SLF049",
    "name": "Eel",
    "category": "Fish",
    "calories_per_100g": 108,
    "protein_g": 20.41,
    "fat_g": 2.63,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf050",
    "food_code": "SLF050",
    "name": "Tilapia",
    "category": "Fish",
    "calories_per_100g": 83,
    "protein_g": 18.48,
    "fat_g": 1.08,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf051",
    "food_code": "SLF051",
    "name": "Prawn, giant freshwater",
    "category": "Seafood",
    "calories_per_100g": 90,
    "protein_g": 19.24,
    "fat_g": 0.52,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf052",
    "food_code": "SLF052",
    "name": "Anchovy sprats, dried (halmasso)",
    "category": "Dried Fish",
    "calories_per_100g": 259,
    "protein_g": 51.16,
    "fat_g": 5.92,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf053",
    "food_code": "SLF053",
    "name": "Baby shrimps, dried (karandi)",
    "category": "Dried Fish",
    "calories_per_100g": 280,
    "protein_g": 61.12,
    "fat_g": 3.74,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf054",
    "food_code": "SLF054",
    "name": "Maldives fish (umbalakada)",
    "category": "Dried Fish",
    "calories_per_100g": 303,
    "protein_g": 61.32,
    "fat_g": 6.26,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf055",
    "food_code": "SLF055",
    "name": "Marlin, dried (Indo-Pacific Sailfish)",
    "category": "Dried Fish",
    "calories_per_100g": 289,
    "protein_g": 54.68,
    "fat_g": 8.04,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf056",
    "food_code": "SLF056",
    "name": "Queenfish, dried",
    "category": "Dried Fish",
    "calories_per_100g": 275,
    "protein_g": 50.04,
    "fat_g": 8.31,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf057",
    "food_code": "SLF057",
    "name": "Shark, dried",
    "category": "Dried Fish",
    "calories_per_100g": 267,
    "protein_g": 55.03,
    "fat_g": 5.25,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf058",
    "food_code": "SLF058",
    "name": "Skipjack tuna, dried",
    "category": "Dried Fish",
    "calories_per_100g": 282,
    "protein_g": 63.79,
    "fat_g": 3.37,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  },
  {
    "id": "slf059",
    "food_code": "SLF059",
    "name": "Smooth belly sardinella, dried",
    "category": "Dried Fish",
    "calories_per_100g": 311,
    "protein_g": 49.6,
    "fat_g": 12.42,
    "carbs_g": 0.0,
    "source": "Sri Lanka Food Composition Table, MRI"
  }
];

async function seedFoods() {
  // Firestore batch limit = 500, so chunk it
  const chunkSize = 499;
  for (let i = 0; i < foods.length; i += chunkSize) {
    const chunk = foods.slice(i, i + chunkSize);
    const batch = db.batch();
    chunk.forEach(food => {
      const ref = db.collection('foods').doc(food.food_code);
      batch.set(ref, food);
    });
    await batch.commit();
    console.log(`Seeded ${i + chunk.length}/${foods.length}...`);
  }
  console.log('Done! All foods seeded.');
  process.exit(0);
}

seedFoods().catch(console.error);